### ISSUE TITLE
Imcompatible with Symfony2.6

### ISSUE THREAD

**Issue by tristanbes** [voryx/restgeneratorbundle#14]
MetadataFactory is no longer present in the shipped version of `DoctrineBundle`

**Comment by davidwdan** [comment]
Thanks @tristanbes I'll take a look at this.

**Comment by vpassapera** [comment]
I fixed this in my fork already. I could cherry pick the commits and do a PR against this?

**Comment by davidwdan** [comment]
That would be great.  I haven't had too much time to work on this project lately, so any help would be appreciated.

**Comment by davidwdan** [comment]
@tristanbes This has been fixed in https://github.com/voryx/restgeneratorbundle/commit/c37e2d2f3deabd49c43e100841bd1df44db1a424
