### ISSUE TITLE
Generate with Mongodb

### ISSUE THREAD

**Issue by renatomefidf** [voryx/restgeneratorbundle#17]
Hello,

I tried your bundle but it only works with doctrine orm, what do you think about mongodb and doctrine odm?

I'm really new at SF2, but if you show me the steps I can try to implement it and send you a PR!

Thank you!

**Comment by davidwdan** [comment]
I haven't done too much with Doctrine ODM, so I'm not exactly sure what would be needed to support it.  I will take a look at it when I get a chance.

**Comment by renatomefidf** [comment]
Please let me know if I can help you!

Maybe if you could create a branch e do the basic structure I can try to finish it!

**Comment by davidwdan** [comment]
@renatomefidf The generator is largely based upon `doctrine:generate:crud`.  If there is a crud generator for mongodb, you should be able to take a look at how that's implemented.

**Comment by davidwdan** [comment]
I'm going to close this issue, since I don't see very much interest in a ODB generator.
