### ISSUE TITLE
Is it possible to install it at Symfony 2.3.27

### ISSUE THREAD

**Issue by zubus** [voryx/restgeneratorbundle#20]
Hello, I got this problem after doing: composer.phar require voryx/restgeneratorbundle dev-master

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for voryx/restgeneratorbundle dev-master -> satisfiable by voryx/restgeneratorbundle[dev-master].
    - voryx/restgeneratorbundle dev-master requires sensio/generator-bundle ~2.5 -> no matching package found.
  Problem 2
    - voryx/restgeneratorbundle dev-master requires sensio/generator-bundle ~2.5 -> no matching package found.
    - symfony/framework-standard-edition 2.3.x-dev requires voryx/restgeneratorbundle dev-master -> satisfiable by voryx/restgeneratorbundle[dev-master].
    - Installation request for symfony/framework-standard-edition 2.3.x-dev -> satisfiable by symfony/framework-standard-edition[2.3.x-dev].

Is it possible to install it at Symfony 2.3.27?

Regards

**Comment by davidwdan** [comment]
Instead of installing dev-master, try installing 0.1.0.

**Comment by zubus** [comment]
Thanks David, with 0.1.0 I get:

Problem 1
    - The requested package sensio/generator-bundle == 2.3.5.0 could not be found.
Problem 2
    - Installation request for voryx/restgeneratorbundle 0.1.0 -> satisfiable by voryx/restgeneratorbundle[0.1.0].
    - Conclusion: remove symfony/symfony v2.3.27
    - voryx/restgeneratorbundle 0.1.0 requires symfony/serializer 2.4.* -> satisfiable by symfony/serializer[v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9].


And with 0.1.1 I get:

Problem 1
    - The requested package sensio/generator-bundle == 2.3.5.0 could not be found.
Problem 2
    - Installation request for sensio/generator-bundle 2.5 -> satisfiable by sensio/generator-bundle[v2.5.0].
    - Conclusion: remove symfony/symfony v2.3.27
    - sensio/generator-bundle v2.5.0 requires symfony/console ~2.5

My Symfony 2.3.27 have a sensio/generator-bundle: 2.5

**Comment by zubus** [comment]
Forget it, I just updated Symfony. Great Bundle ;)
