### ISSUE TITLE
Can't install Bundle (missing jms-serializer)

### ISSUE THREAD

**Issue by kaiszy** [voryx/restgeneratorbundle#27]
Hi,

when i try to install the restgeneratorbundle i get:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for voryx/restgeneratorbundle ^0.2.0 -> satisfiable by voryx/restgeneratorbundl
    - voryx/restgeneratorbundle 0.2.0 requires jms/serializer-bundle 0.13.* -> no matching package found.

jms/serializer-bundle is installed in a newer version:

        "jms/serializer-bundle": "^1.0",

Maybe the composer.json have to be updated ? :)

CU,
  Kai.

**Comment by davidwdan** [comment]
@kaiszy what steps can I take to reproduce this problem?  I've installed the bundle on symfony versions 2.6 and 2.7 without any errors.

**Comment by kaiszy** [comment]
Hi!

I use Symfony 2.7 with the following Bundles installed:

        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/migrations": "^1.0",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "phpunit/phpunit": "^4.7",
        "knplabs/knp-paginator-bundle": "^2.4",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "friendsofsymfony/rest-bundle": "^1.7",
        "vmelnik/doctrine-encrypt-bundle": "dev-master",
        "jms/serializer-bundle": "^1.0",
        "sllh/iso-codes-validator": "^1.1",
        "bav/symfony": "^1.0",
        "nelmio/api-doc-bundle": "^2.9"

You see serializer 1.0.

When i make a

  composer require voryx/restgeneratorbundle

i get

Using version ^0.2.0 for voryx/restgeneratorbundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for voryx/restgeneratorbundle ^0.2.0 -> satisfiable by voryx/restgeneratorbundle[0.2.0].
    - voryx/restgeneratorbundle 0.2.0 requires jms/serializer-bundle 0.13.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

CU,
  Kai.

**Comment by davidwdan** [comment]
Okay, that makes more sense.  I'll need to update the package, but in the meantime, you can do this in your composer.json:

```"jms/serializer-bundle": "1.0.0 as 0.13.0"```

**Comment by kaiszy** [comment]
Hi,

ok..i really did it ;)

Result:


  - Removing jms/serializer (1.0.0)
  - Installing jms/serializer (0.16.0)
    Downloading: 100%

  - Removing jms/serializer-bundle (1.0.0)
  - Installing jms/serializer-bundle (0.13.0)
    Downloading: 100%

and

Using version ^0.2.0 for voryx/restgeneratorbundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing nelmio/cors-bundle (1.4.0)
    Loading from cache

  - Installing voryx/restgeneratorbundle (0.2.0)
    Downloading: 100%

Writing lock file
[...]

Looks good :)

CU,
 Kai.

**Comment by davidwdan** [comment]
Fixed in https://github.com/voryx/restgeneratorbundle/commit/27c467c9da9b1abe0e16d913d98eb7d59eeaa473
